"""add scm purchase orders and audit

Revision ID: 23a5f8a99a0b
Revises: 58b3dd5878cd
Create Date: 2026-07-21 14:12:03.500740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a5f8a99a0b'
down_revision = '58b3dd5878cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scm_proveedor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=64), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('ruc', sa.String(length=11), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('codigo = upper(trim(codigo)) AND length(codigo) > 0', name='ck_scm_proveedor_codigo_normalizado'),
    sa.CheckConstraint('ruc IS NULL OR length(ruc) = 11', name='ck_scm_proveedor_ruc_longitud'),
    sa.CheckConstraint('version > 0', name='ck_scm_proveedor_version'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_scm_proveedor_codigo'),
    sa.UniqueConstraint('ruc', name='uq_scm_proveedor_ruc')
    )
    op.create_table('scm_operacion',
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('request_sha256', sa.String(length=64), nullable=False),
    sa.Column('estado_http', sa.Integer(), nullable=True),
    sa.Column('response_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('estado_http IS NULL OR estado_http BETWEEN 100 AND 599', name='ck_scm_operacion_estado_http'),
    sa.CheckConstraint('length(request_sha256) = 64', name='ck_scm_operacion_request_sha256'),
    sa.ForeignKeyConstraint(['actor_id'], ['trabajador.id'], name='fk_scm_operacion_actor', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('operation_id')
    )
    op.create_table('scm_orden_compra',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=64), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='ACTIVA', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('codigo = upper(trim(codigo)) AND length(codigo) > 0', name='ck_scm_orden_compra_codigo_normalizado'),
    sa.CheckConstraint("estado IN ('ACTIVA', 'CERRADA', 'ANULADA')", name='ck_scm_orden_compra_estado'),
    sa.CheckConstraint('version > 0', name='ck_scm_orden_compra_version'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['scm_proveedor.id'], name='fk_scm_orden_compra_proveedor', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_scm_orden_compra_codigo')
    )
    op.create_table('scm_evento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('actor_snapshot', sa.JSON(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('operation_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['trabajador.id'], name='fk_scm_evento_actor', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operation_id'], ['scm_operacion.operation_id'], name='fk_scm_evento_operacion', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scm_evento', schema=None) as batch_op:
        batch_op.create_index('ix_scm_evento_aggregate', ['aggregate_type', 'aggregate_id'], unique=False)

    op.create_table('scm_orden_compra_revision',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=30), server_default='BORRADOR', nullable=False),
    sa.Column('creada_por_id', sa.Integer(), nullable=False),
    sa.Column('enviada_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aprobada_por_id', sa.Integer(), nullable=True),
    sa.Column('aprobada_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("estado NOT IN ('APROBADA', 'SUPERADA') OR (aprobada_por_id IS NOT NULL AND aprobada_at IS NOT NULL)", name='ck_scm_orden_compra_revision_aprobacion_coherente'),
    sa.CheckConstraint("estado IN ('BORRADOR', 'PENDIENTE_APROBACION', 'APROBADA', 'RECHAZADA', 'SUPERADA')", name='ck_scm_orden_compra_revision_estado'),
    sa.CheckConstraint('aprobada_por_id IS NULL OR aprobada_por_id <> creada_por_id', name='ck_scm_orden_compra_revision_actores_distintos'),
    sa.CheckConstraint("estado NOT IN ('PENDIENTE_APROBACION', 'APROBADA', 'SUPERADA') OR enviada_at IS NOT NULL", name='ck_scm_orden_compra_revision_envio_coherente'),
    sa.CheckConstraint('numero > 0', name='ck_scm_orden_compra_revision_numero'),
    sa.CheckConstraint('version > 0', name='ck_scm_orden_compra_revision_version'),
    sa.ForeignKeyConstraint(['aprobada_por_id'], ['trabajador.id'], name='fk_scm_orden_compra_revision_aprobada_por', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['creada_por_id'], ['trabajador.id'], name='fk_scm_orden_compra_revision_creada_por', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['orden_id'], ['scm_orden_compra.id'], name='fk_scm_orden_compra_revision_orden', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orden_id', 'numero', name='uq_scm_orden_compra_revision_orden_numero')
    )
    with op.batch_alter_table('scm_orden_compra_revision', schema=None) as batch_op:
        batch_op.create_index('ux_scm_oc_revision_abierta_orden', ['orden_id'], unique=True, postgresql_where=sa.text("estado IN ('BORRADOR', 'PENDIENTE_APROBACION')"), sqlite_where=sa.text("estado IN ('BORRADOR', 'PENDIENTE_APROBACION')"))
        batch_op.create_index('ux_scm_oc_revision_aprobada_orden', ['orden_id'], unique=True, postgresql_where=sa.text("estado = 'APROBADA'"), sqlite_where=sa.text("estado = 'APROBADA'"))

    op.create_table('scm_orden_compra_linea',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('numero_linea', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_autorizada_kg', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('fecha_requerida', sa.Date(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.CheckConstraint('cantidad_autorizada_kg > 0', name='ck_scm_orden_compra_linea_cantidad_positiva'),
    sa.CheckConstraint('numero_linea > 0', name='ck_scm_orden_compra_linea_numero'),
    sa.ForeignKeyConstraint(['material_id'], ['scm_material.id'], name='fk_scm_orden_compra_linea_material', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revision_id'], ['scm_orden_compra_revision.id'], name='fk_scm_orden_compra_linea_revision', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id', 'numero_linea', name='uq_scm_orden_compra_linea_revision_numero')
    )
    op.execute(sa.text("""
        CREATE FUNCTION scm_impedir_mutacion_evento()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'scm_evento es append-only'
                USING ERRCODE = '55000';
        END
        $$
    """))
    op.execute(sa.text("""
        CREATE TRIGGER trg_scm_evento_append_only
        BEFORE UPDATE OR DELETE ON scm_evento
        FOR EACH ROW EXECUTE FUNCTION scm_impedir_mutacion_evento()
    """))
    op.execute(sa.text("""
        CREATE FUNCTION scm_validar_mutacion_linea_oc()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            estado_revision varchar(30);
        BEGIN
            IF TG_OP IN ('UPDATE', 'DELETE') THEN
                SELECT estado INTO estado_revision
                FROM scm_orden_compra_revision
                WHERE id = OLD.revision_id;
                IF estado_revision <> 'BORRADOR' THEN
                    RAISE EXCEPTION
                        'las lineas de una revision no borrador son inmutables'
                        USING ERRCODE = '55000';
                END IF;
            END IF;

            IF TG_OP IN ('INSERT', 'UPDATE') THEN
                SELECT estado INTO estado_revision
                FROM scm_orden_compra_revision
                WHERE id = NEW.revision_id;
                IF estado_revision <> 'BORRADOR' THEN
                    RAISE EXCEPTION
                        'solo una revision borrador admite lineas'
                        USING ERRCODE = '55000';
                END IF;
                RETURN NEW;
            END IF;
            RETURN OLD;
        END
        $$
    """))
    op.execute(sa.text("""
        CREATE TRIGGER trg_scm_oc_linea_revision_mutable
        BEFORE INSERT OR UPDATE OR DELETE ON scm_orden_compra_linea
        FOR EACH ROW EXECUTE FUNCTION scm_validar_mutacion_linea_oc()
    """))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM scm_proveedor)
               OR EXISTS (SELECT 1 FROM scm_operacion)
               OR EXISTS (SELECT 1 FROM scm_evento)
               OR EXISTS (SELECT 1 FROM scm_orden_compra)
               OR EXISTS (SELECT 1 FROM scm_orden_compra_revision)
               OR EXISTS (SELECT 1 FROM scm_orden_compra_linea) THEN
                RAISE EXCEPTION
                    'US010A compras contiene datos; downgrade destructivo bloqueado';
            END IF;
        END
        $$
    """))
    op.execute(sa.text(
        'DROP TRIGGER trg_scm_oc_linea_revision_mutable '
        'ON scm_orden_compra_linea'
    ))
    op.execute(sa.text('DROP FUNCTION scm_validar_mutacion_linea_oc()'))
    op.execute(sa.text('DROP TRIGGER trg_scm_evento_append_only ON scm_evento'))
    op.execute(sa.text('DROP FUNCTION scm_impedir_mutacion_evento()'))
    op.drop_table('scm_orden_compra_linea')
    with op.batch_alter_table('scm_orden_compra_revision', schema=None) as batch_op:
        batch_op.drop_index('ux_scm_oc_revision_aprobada_orden', postgresql_where=sa.text("estado = 'APROBADA'"), sqlite_where=sa.text("estado = 'APROBADA'"))
        batch_op.drop_index('ux_scm_oc_revision_abierta_orden', postgresql_where=sa.text("estado IN ('BORRADOR', 'PENDIENTE_APROBACION')"), sqlite_where=sa.text("estado IN ('BORRADOR', 'PENDIENTE_APROBACION')"))

    op.drop_table('scm_orden_compra_revision')
    with op.batch_alter_table('scm_evento', schema=None) as batch_op:
        batch_op.drop_index('ix_scm_evento_aggregate')

    op.drop_table('scm_evento')
    op.drop_table('scm_orden_compra')
    op.drop_table('scm_operacion')
    op.drop_table('scm_proveedor')
    # ### end Alembic commands ###
