"""legacy schema baseline

Revision ID: f02b00ae2e67
Revises: 
Create Date: 2026-07-21 12:54:10.808149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f02b00ae2e67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estacion_pesaje',
    sa.Column('station_id', sa.String(length=36), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=False),
    sa.Column('estado_admin', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('station_id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('familia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('familia_color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('linea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('molde',
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('peso_tiro_gr', sa.Float(), nullable=False),
    sa.Column('tiempo_ciclo_std', sa.Float(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('rol_operativo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('talonario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desde', sa.Integer(), nullable=False),
    sa.Column('hasta', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('ultimo_usado', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_maquina',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('proceso', sa.String(length=50), nullable=False),
    sa.Column('fabricante', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('capacidad_toneladas', sa.Float(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('trabajador',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('nombre_corto', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('color_produccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color_base_id', sa.Integer(), nullable=False),
    sa.Column('familia_color_id', sa.Integer(), nullable=False),
    sa.Column('codigo_legacy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['color_base_id'], ['color_base.id'], ),
    sa.ForeignKeyConstraint(['familia_color_id'], ['familia_color.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('color_base_id', 'familia_color_id', name='uix_color_base_familia')
    )
    op.create_table('estacion_comando_piloto',
    sa.Column('command_id', sa.String(length=36), nullable=False),
    sa.Column('station_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('legacy_pesaje_id', sa.Integer(), nullable=True),
    sa.Column('op_raw', sa.String(length=50), nullable=True),
    sa.Column('requested_by', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['estacion_pesaje.station_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('command_id')
    )
    with op.batch_alter_table('estacion_comando_piloto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estacion_comando_piloto_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_estacion_comando_piloto_station_id'), ['station_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_estacion_comando_piloto_status'), ['status'], unique=False)

    op.create_table('estacion_delta_pesaje_legacy',
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('station_id', sa.String(length=36), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('rows_received', sa.Integer(), nullable=False),
    sa.Column('rows_created', sa.Integer(), nullable=False),
    sa.Column('high_watermark', sa.Integer(), nullable=False),
    sa.Column('received_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['estacion_pesaje.station_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('batch_id')
    )
    with op.batch_alter_table('estacion_delta_pesaje_legacy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estacion_delta_pesaje_legacy_station_id'), ['station_id'], unique=False)

    op.create_table('estacion_estado_actual',
    sa.Column('station_id', sa.String(length=36), nullable=False),
    sa.Column('heartbeat_id', sa.String(length=36), nullable=False),
    sa.Column('boot_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('generated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('clock_skew_seconds', sa.Float(), nullable=False),
    sa.Column('app_version', sa.String(length=50), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('process_state', sa.String(length=30), nullable=False),
    sa.Column('database_state', sa.String(length=30), nullable=False),
    sa.Column('scale_state', sa.String(length=40), nullable=False),
    sa.Column('printer_state', sa.String(length=30), nullable=False),
    sa.Column('catalog_state', sa.String(length=30), nullable=False),
    sa.Column('communication_state', sa.String(length=40), nullable=False),
    sa.Column('last_central_ack_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('legacy_unsynced_count', sa.Integer(), nullable=False),
    sa.Column('oldest_legacy_unsynced_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('context_json', sa.Text(), nullable=False),
    sa.Column('last_capture_json', sa.Text(), nullable=True),
    sa.Column('local_summary_json', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['estacion_pesaje.station_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('station_id'),
    sa.UniqueConstraint('heartbeat_id')
    )
    op.create_table('estacion_estado_historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(length=36), nullable=False),
    sa.Column('heartbeat_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('occurred_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['estacion_pesaje.station_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('estacion_estado_historial', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estacion_estado_historial_station_id'), ['station_id'], unique=False)

    op.create_table('estacion_heartbeat_recepcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heartbeat_id', sa.String(length=36), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('station_id', sa.String(length=36), nullable=False),
    sa.Column('boot_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('generated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('applied_to_current', sa.Boolean(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['estacion_pesaje.station_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('heartbeat_id')
    )
    with op.batch_alter_table('estacion_heartbeat_recepcion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estacion_heartbeat_recepcion_station_id'), ['station_id'], unique=False)

    op.create_table('estacion_importacion_pesaje_legacy',
    sa.Column('import_id', sa.String(length=36), nullable=False),
    sa.Column('station_id', sa.String(length=36), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('source_schema_version', sa.Integer(), nullable=False),
    sa.Column('source_total_rows', sa.Integer(), nullable=False),
    sa.Column('source_active_rows', sa.Integer(), nullable=False),
    sa.Column('source_deleted_rows', sa.Integer(), nullable=False),
    sa.Column('source_first_capture_local', sa.String(length=40), nullable=True),
    sa.Column('source_last_capture_local', sa.String(length=40), nullable=True),
    sa.Column('manifest_json', sa.Text(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('chunks_received', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['estacion_pesaje.station_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('import_id'),
    sa.UniqueConstraint('station_id', 'source_sha256', name='uq_importacion_legacy_estacion_fuente')
    )
    with op.batch_alter_table('estacion_importacion_pesaje_legacy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estacion_importacion_pesaje_legacy_station_id'), ['station_id'], unique=False)

    op.create_table('estacion_reporte_avance_recepcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('station_id', sa.String(length=36), nullable=False),
    sa.Column('generated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_start_date', sa.Date(), nullable=False),
    sa.Column('window_end_date', sa.Date(), nullable=False),
    sa.Column('rows_count', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['estacion_pesaje.station_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    with op.batch_alter_table('estacion_reporte_avance_recepcion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estacion_reporte_avance_recepcion_station_id'), ['station_id'], unique=False)

    op.create_table('maquina',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo_maquina_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['tipo_maquina_id'], ['tipo_maquina.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('pieza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('molde_id', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('linea_id', sa.Integer(), nullable=True),
    sa.Column('familia_id', sa.Integer(), nullable=True),
    sa.Column('cavidades', sa.Integer(), nullable=False),
    sa.Column('peso_unitario_gr', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['familia_id'], ['familia.id'], ),
    sa.ForeignKeyConstraint(['linea_id'], ['linea.id'], ),
    sa.ForeignKeyConstraint(['molde_id'], ['molde.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('molde_id', 'nombre', name='uq_molde_pieza_nombre')
    )
    op.create_table('producto_terminado',
    sa.Column('linea_id', sa.Integer(), nullable=False),
    sa.Column('familia_id', sa.Integer(), nullable=False),
    sa.Column('cod_producto', sa.Integer(), nullable=True),
    sa.Column('producto', sa.String(length=200), nullable=True),
    sa.Column('cod_sku_pt', sa.String(length=50), nullable=False),
    sa.Column('um', sa.String(length=20), nullable=True),
    sa.Column('doc_x_paq', sa.Integer(), nullable=True),
    sa.Column('doc_x_bulto', sa.Integer(), nullable=True),
    sa.Column('peso_g', sa.Float(), nullable=True),
    sa.Column('precio_estimado', sa.Float(), nullable=True),
    sa.Column('precio_sin_igv', sa.Float(), nullable=True),
    sa.Column('indicador_x_kg', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('codigo_barra', sa.String(length=50), nullable=True),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('nombre_gs1', sa.String(length=200), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('estado_revision', sa.String(length=20), nullable=True),
    sa.Column('fecha_importacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_revision', sa.DateTime(), nullable=True),
    sa.Column('notas_revision', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['familia_id'], ['familia.id'], ),
    sa.ForeignKeyConstraint(['linea_id'], ['linea.id'], ),
    sa.PrimaryKeyConstraint('cod_sku_pt')
    )
    op.create_table('trabajador_rol',
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('rol_operativo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_operativo_id'], ['rol_operativo.id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajador.id'], ),
    sa.PrimaryKeyConstraint('trabajador_id', 'rol_operativo_id')
    )
    op.create_table('colorante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estacion_avance_produccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('operational_date', sa.Date(), nullable=False),
    sa.Column('group_key', sa.String(length=64), nullable=False),
    sa.Column('op', sa.String(length=20), nullable=True),
    sa.Column('ot', sa.String(length=20), nullable=True),
    sa.Column('mold', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('machine_code', sa.String(length=50), nullable=True),
    sa.Column('shift', sa.String(length=20), nullable=True),
    sa.Column('bags', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('first_capture_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_capture_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_received_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['estacion_reporte_avance_recepcion.report_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['station_id'], ['estacion_pesaje.station_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'operational_date', 'group_key', name='uq_estacion_avance_grupo')
    )
    with op.batch_alter_table('estacion_avance_produccion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estacion_avance_produccion_machine_code'), ['machine_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_estacion_avance_produccion_op'), ['op'], unique=False)
        batch_op.create_index(batch_op.f('ix_estacion_avance_produccion_operational_date'), ['operational_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_estacion_avance_produccion_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_estacion_avance_produccion_shift'), ['shift'], unique=False)
        batch_op.create_index(batch_op.f('ix_estacion_avance_produccion_station_id'), ['station_id'], unique=False)

    op.create_table('estacion_cierre_op_legacy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=False),
    sa.Column('station_id', sa.String(length=36), nullable=False),
    sa.Column('op_raw', sa.String(length=50), nullable=False),
    sa.Column('op_normalized', sa.String(length=50), nullable=False),
    sa.Column('mold_raw', sa.String(length=300), nullable=True),
    sa.Column('reason_raw', sa.String(length=500), nullable=True),
    sa.Column('closed_at_local', sa.String(length=40), nullable=False),
    sa.Column('closed_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['estacion_importacion_pesaje_legacy.import_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['estacion_pesaje.station_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_id', 'station_id', 'op_raw', name='uq_importacion_cierre_op_legacy')
    )
    with op.batch_alter_table('estacion_cierre_op_legacy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estacion_cierre_op_legacy_import_id'), ['import_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_estacion_cierre_op_legacy_op_raw'), ['op_raw'], unique=False)
        batch_op.create_index(batch_op.f('ix_estacion_cierre_op_legacy_station_id'), ['station_id'], unique=False)

    op.create_table('estacion_importacion_pesaje_legacy_chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('rows_count', sa.Integer(), nullable=False),
    sa.Column('received_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['estacion_importacion_pesaje_legacy.import_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_id', 'chunk_index', name='uq_importacion_legacy_chunk')
    )
    with op.batch_alter_table('estacion_importacion_pesaje_legacy_chunk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estacion_importacion_pesaje_legacy_chunk_import_id'), ['import_id'], unique=False)

    op.create_table('estacion_pesaje_legacy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(length=36), nullable=False),
    sa.Column('legacy_pesaje_id', sa.Integer(), nullable=False),
    sa.Column('first_import_id', sa.String(length=36), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('captured_at_local', sa.String(length=40), nullable=False),
    sa.Column('captured_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('operational_date', sa.Date(), nullable=False),
    sa.Column('deleted_at_local', sa.String(length=40), nullable=True),
    sa.Column('deleted_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('op_raw', sa.String(length=50), nullable=True),
    sa.Column('op_normalized', sa.String(length=50), nullable=True),
    sa.Column('op_resolution_status', sa.String(length=30), nullable=False),
    sa.Column('ot_raw', sa.String(length=50), nullable=True),
    sa.Column('ot_normalized', sa.String(length=50), nullable=True),
    sa.Column('mold_raw', sa.String(length=300), nullable=True),
    sa.Column('mold_normalized', sa.String(length=300), nullable=True),
    sa.Column('color_raw', sa.String(length=300), nullable=True),
    sa.Column('color_normalized', sa.String(length=300), nullable=True),
    sa.Column('machine_raw', sa.String(length=100), nullable=True),
    sa.Column('machine_normalized', sa.String(length=100), nullable=True),
    sa.Column('shift_raw', sa.String(length=100), nullable=True),
    sa.Column('shift_normalized', sa.String(length=100), nullable=True),
    sa.Column('operator_raw', sa.String(length=300), nullable=True),
    sa.Column('operator_normalized', sa.String(length=300), nullable=True),
    sa.Column('raw_payload_json', sa.Text(), nullable=False),
    sa.Column('imported_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['first_import_id'], ['estacion_importacion_pesaje_legacy.import_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['station_id'], ['estacion_pesaje.station_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'legacy_pesaje_id', name='uq_pesaje_legacy_estacion_id')
    )
    with op.batch_alter_table('estacion_pesaje_legacy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estacion_pesaje_legacy_captured_at_utc'), ['captured_at_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_estacion_pesaje_legacy_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_estacion_pesaje_legacy_op_normalized'), ['op_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_estacion_pesaje_legacy_op_raw'), ['op_raw'], unique=False)
        batch_op.create_index(batch_op.f('ix_estacion_pesaje_legacy_op_resolution_status'), ['op_resolution_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_estacion_pesaje_legacy_operational_date'), ['operational_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_estacion_pesaje_legacy_station_id'), ['station_id'], unique=False)

    op.create_table('materia_prima',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orden_produccion',
    sa.Column('numero_op', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('maquina_id', sa.Integer(), nullable=True),
    sa.Column('maquina_codigo_snapshot', sa.String(length=20), nullable=True),
    sa.Column('maquina_nombre_snapshot', sa.String(length=100), nullable=True),
    sa.Column('producto_sku', sa.String(length=50), nullable=True),
    sa.Column('producto', sa.String(length=100), nullable=True),
    sa.Column('molde', sa.String(length=100), nullable=True),
    sa.Column('molde_id', sa.String(length=50), nullable=True),
    sa.Column('snapshot_tiempo_ciclo', sa.Float(), nullable=True),
    sa.Column('snapshot_horas_turno', sa.Float(), nullable=True),
    sa.Column('snapshot_peso_colada_gr', sa.Float(), nullable=True),
    sa.Column('ciclos', sa.Float(), nullable=True),
    sa.Column('tipo_cambio', sa.Float(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('calculo_peso_tiro_gr', sa.Float(), nullable=True),
    sa.Column('calculo_peso_neto_golpe', sa.Float(), nullable=True),
    sa.Column('calculo_cavidades_totales', sa.Integer(), nullable=True),
    sa.Column('calculo_peso_produccion', sa.Float(), nullable=True),
    sa.Column('calculo_merma_pct', sa.Float(), nullable=True),
    sa.Column('calculo_peso_inc_merma', sa.Float(), nullable=True),
    sa.Column('calculo_merma_natural_kg', sa.Float(), nullable=True),
    sa.Column('calculo_horas', sa.Float(), nullable=True),
    sa.Column('calculo_dias', sa.Float(), nullable=True),
    sa.Column('calculo_fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('calculo_colores_activos', sa.Integer(), nullable=True),
    sa.Column('calculo_familia_color', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquina.id'], ),
    sa.ForeignKeyConstraint(['molde_id'], ['molde.codigo'], ),
    sa.ForeignKeyConstraint(['producto_sku'], ['producto_terminado.cod_sku_pt'], ),
    sa.PrimaryKeyConstraint('numero_op')
    )
    op.create_table('pieza_color',
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('linea_id', sa.Integer(), nullable=False),
    sa.Column('familia_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('pieza_id', sa.Integer(), nullable=True),
    sa.Column('cod_pieza', sa.Integer(), nullable=True),
    sa.Column('piezas', sa.String(length=200), nullable=True),
    sa.Column('color_produccion_id', sa.Integer(), nullable=True),
    sa.Column('cavidad', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('cod_extru', sa.Integer(), nullable=True),
    sa.Column('tipo_extruccion', sa.String(length=50), nullable=True),
    sa.Column('cod_mp', sa.String(length=50), nullable=True),
    sa.Column('mp', sa.String(length=100), nullable=True),
    sa.Column('estado_revision', sa.String(length=20), nullable=True),
    sa.Column('fecha_importacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_revision', sa.DateTime(), nullable=True),
    sa.Column('notas_revision', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['color_produccion_id'], ['color_produccion.id'], ),
    sa.ForeignKeyConstraint(['familia_id'], ['familia.id'], ),
    sa.ForeignKeyConstraint(['linea_id'], ['linea.id'], ),
    sa.ForeignKeyConstraint(['pieza_id'], ['pieza.id'], ),
    sa.PrimaryKeyConstraint('sku'),
    sa.UniqueConstraint('pieza_id', 'color_produccion_id', name='uq_pieza_color')
    )
    op.create_table('estacion_importacion_pesaje_legacy_fila',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=False),
    sa.Column('capture_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capture_id'], ['estacion_pesaje_legacy.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_id'], ['estacion_importacion_pesaje_legacy.import_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_id', 'capture_id', name='uq_importacion_legacy_fila')
    )
    with op.batch_alter_table('estacion_importacion_pesaje_legacy_fila', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estacion_importacion_pesaje_legacy_fila_capture_id'), ['capture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_estacion_importacion_pesaje_legacy_fila_import_id'), ['import_id'], unique=False)

    op.create_table('historial_estado_orden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_op', sa.String(length=20), nullable=False),
    sa.Column('estado_anterior', sa.Boolean(), nullable=True),
    sa.Column('estado_nuevo', sa.Boolean(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('usuario', sa.String(length=100), nullable=True),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['numero_op'], ['orden_produccion.numero_op'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lote_color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_op', sa.String(length=20), nullable=False),
    sa.Column('color_produccion_id', sa.Integer(), nullable=True),
    sa.Column('producto_sku_output', sa.String(length=50), nullable=True),
    sa.Column('meta_kg', sa.Float(), nullable=False),
    sa.Column('personas', sa.Integer(), nullable=True),
    sa.Column('calculo_coladas', sa.Float(), nullable=True),
    sa.Column('calculo_kg_real', sa.Float(), nullable=True),
    sa.Column('calculo_horas_hombre', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['color_produccion_id'], ['color_produccion.id'], ),
    sa.ForeignKeyConstraint(['numero_op'], ['orden_produccion.numero_op'], ),
    sa.ForeignKeyConstraint(['producto_sku_output'], ['producto_terminado.cod_sku_pt'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pieza_componente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kit_sku', sa.String(length=50), nullable=False),
    sa.Column('componente_sku', sa.String(length=50), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['componente_sku'], ['pieza_color.sku'], ),
    sa.ForeignKeyConstraint(['kit_sku'], ['pieza_color.sku'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kit_sku', 'componente_sku', name='uq_pieza_componente')
    )
    op.create_table('producto_pieza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_terminado_id', sa.String(length=50), nullable=False),
    sa.Column('pieza_sku', sa.String(length=50), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pieza_sku'], ['pieza_color.sku'], ),
    sa.ForeignKeyConstraint(['producto_terminado_id'], ['producto_terminado.cod_sku_pt'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_terminado_id', 'pieza_sku', name='uq_producto_pieza')
    )
    op.create_table('receta_color_normalizada',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('color_produccion_id', sa.Integer(), nullable=False),
    sa.Column('colorante_id', sa.Integer(), nullable=False),
    sa.Column('producto_sku', sa.String(length=50), nullable=True),
    sa.Column('gr_por_kg', sa.Float(), nullable=False),
    sa.Column('n_muestras', sa.Integer(), nullable=False),
    sa.Column('ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['color_produccion_id'], ['color_produccion.id'], ),
    sa.ForeignKeyConstraint(['colorante_id'], ['colorante.id'], ),
    sa.ForeignKeyConstraint(['producto_sku'], ['producto_terminado.cod_sku_pt'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('color_produccion_id', 'colorante_id', 'producto_sku', name='uq_receta_color_normalizada')
    )
    op.create_table('registro_diario_produccion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orden_id', sa.String(length=20), nullable=False),
    sa.Column('maquina_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('turno', sa.String(length=20), nullable=True),
    sa.Column('hora_inicio', sa.String(length=10), nullable=True),
    sa.Column('hora_fin', sa.String(length=10), nullable=True),
    sa.Column('colada_inicial', sa.Integer(), nullable=True),
    sa.Column('colada_final', sa.Integer(), nullable=True),
    sa.Column('tiempo_ciclo_reportado', sa.Float(), nullable=True),
    sa.Column('cantidad_por_hora_meta', sa.Integer(), nullable=True),
    sa.Column('tiempo_enfriamiento', sa.Float(), nullable=True),
    sa.Column('snapshot_cavidades', sa.Integer(), nullable=True),
    sa.Column('snapshot_peso_neto_gr', sa.Float(), nullable=True),
    sa.Column('snapshot_peso_colada_gr', sa.Float(), nullable=True),
    sa.Column('snapshot_peso_extra_gr', sa.Float(), nullable=True),
    sa.Column('maquina_codigo_snapshot', sa.String(length=20), nullable=True),
    sa.Column('maquina_nombre_snapshot', sa.String(length=100), nullable=True),
    sa.Column('total_coladas_calculada', sa.Integer(), nullable=True),
    sa.Column('total_piezas_buenas', sa.Integer(), nullable=True),
    sa.Column('total_kg_real', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquina.id'], ),
    sa.ForeignKeyConstraint(['orden_id'], ['orden_produccion.numero_op'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshot_composicion_molde',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orden_id', sa.String(length=20), nullable=False),
    sa.Column('pieza_sku', sa.String(length=50), nullable=True),
    sa.Column('cavidades', sa.Integer(), nullable=False),
    sa.Column('peso_unit_gr', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['orden_produccion.numero_op'], ),
    sa.ForeignKeyConstraint(['pieza_sku'], ['pieza_color.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control_peso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('peso_real_kg', sa.Float(), nullable=False),
    sa.Column('color_nombre', sa.String(length=50), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('hora_registro', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['color_produccion.id'], ),
    sa.ForeignKeyConstraint(['registro_id'], ['registro_diario_produccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_produccion_hora',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('hora', sa.String(length=10), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=True),
    sa.Column('maquinista_snapshot', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.Column('coladas_realizadas', sa.Integer(), nullable=True),
    sa.Column('cantidad_piezas', sa.Integer(), nullable=True),
    sa.Column('kg_producidos', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['registro_id'], ['registro_diario_produccion.id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('se_colorea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('colorante_id', sa.Integer(), nullable=False),
    sa.Column('gramos', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['colorante_id'], ['colorante.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lote_color.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('se_compone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('materia_prima_id', sa.Integer(), nullable=False),
    sa.Column('fraccion', sa.Float(), nullable=False),
    sa.Column('calculo_peso_kg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lote_color.id'], ),
    sa.ForeignKeyConstraint(['materia_prima_id'], ['materia_prima.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario_manga',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pesaje_id', sa.Integer(), nullable=False),
    sa.Column('control_peso_id', sa.Integer(), nullable=True),
    sa.Column('nro_op', sa.String(length=20), nullable=True),
    sa.Column('molde', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.Column('pieza_sku', sa.String(length=50), nullable=True),
    sa.Column('pieza_nombre', sa.String(length=100), nullable=True),
    sa.Column('extra1', sa.String(length=200), nullable=True),
    sa.Column('extra2', sa.String(length=200), nullable=True),
    sa.Column('extra3', sa.String(length=200), nullable=True),
    sa.Column('locacion_actual', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=True),
    sa.Column('fecha_despacho', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['control_peso_id'], ['control_peso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventario_manga', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventario_manga_pesaje_id'), ['pesaje_id'], unique=True)

    op.create_table('movimiento_kardex',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inventario_manga_id', sa.Integer(), nullable=False),
    sa.Column('tipo_operacion', sa.String(length=30), nullable=False),
    sa.Column('locacion_origen', sa.String(length=100), nullable=True),
    sa.Column('locacion_destino', sa.String(length=100), nullable=True),
    sa.Column('operario_id', sa.String(length=50), nullable=True),
    sa.Column('metadatos', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inventario_manga_id'], ['inventario_manga.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    raise RuntimeError(
        "La línea base legacy es irreversible. "
        "Use la revisión f02b00ae2e67 como límite de rollback."
    )
