import importlib
import os
from uuid import uuid4

import pytest
from alembic.migration import MigrationContext
from alembic.operations import Operations
from sqlalchemy import create_engine, text


MIGRATION_MODULE = (
    "migrations.versions."
    "f89d4e6a8c53_guard_excluded_pilot_capabilities"
)
GUARDED_CAPABILITIES = {
    "OPM_VER",
    "OPM_CREAR",
    "OPM_LIBERAR",
    "OPM_EJECUTAR",
    "OPM_PESO_CONFIRMAR",
    "OPM_CERRAR",
    "MATERIAL_PREPARADO_RECIBIR",
    "MATERIAL_PREPARADO_CALIDAD_RESOLVER",
    "MATERIAL_PREPARADO_RESERVAR",
    "MATERIAL_PREPARADO_EMITIR",
    "MATERIAL_PREPARADO_RECIBIR_MAQUINA",
    "MATERIAL_PREPARADO_CONSUMIR",
    "MATERIAL_PREPARADO_DEVOLVER",
    "MATERIAL_PREPARADO_GENEALOGIA_VER",
    "MANGA_FINALIZAR_PARCIAL",
}
K1_CAPABILITIES = {
    "MANGA_CONTROL_PESO_REGISTRAR",
    "MANGA_TRANSFERIR_OT",
}


def _previous_schema(connection):
    identity = (
        "INTEGER PRIMARY KEY AUTOINCREMENT"
        if connection.dialect.name == "sqlite"
        else "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    )
    connection.execute(text(f"""
        CREATE TABLE rol_operativo (
            id {identity},
            codigo VARCHAR(50) NOT NULL UNIQUE,
            nombre VARCHAR(100) NOT NULL,
            activo BOOLEAN NOT NULL DEFAULT true
        )
    """))
    connection.execute(text(f"""
        CREATE TABLE scm_capacidad (
            id {identity},
            codigo VARCHAR(96) NOT NULL UNIQUE,
            nombre VARCHAR(200) NOT NULL,
            activo BOOLEAN NOT NULL DEFAULT true
        )
    """))
    connection.execute(text("""
        CREATE TABLE scm_rol_capacidad (
            rol_operativo_id INTEGER NOT NULL,
            capacidad_id INTEGER NOT NULL,
            PRIMARY KEY (rol_operativo_id, capacidad_id)
        )
    """))
    connection.execute(text("""
        INSERT INTO rol_operativo (codigo, nombre, activo) VALUES
          ('PREPARADOR_MATERIAL', 'Preparador de material', true),
          ('GERENTE_GENERAL', 'Gerente General', true)
    """))
    for code in sorted(
        GUARDED_CAPABILITIES | K1_CAPABILITIES | {"INVENTARIO_VER"}
    ):
        connection.execute(text("""
            INSERT INTO scm_capacidad (codigo, nombre, activo)
            VALUES (:code, :code, true)
        """), {"code": code})
    connection.execute(text("""
        INSERT INTO scm_rol_capacidad (rol_operativo_id, capacidad_id)
        SELECT role.id, capability.id
        FROM rol_operativo role
        CROSS JOIN scm_capacidad capability
        WHERE role.codigo = 'GERENTE_GENERAL'
           OR (
             role.codigo = 'PREPARADOR_MATERIAL'
             AND capability.codigo IN ('OPM_VER', 'INVENTARIO_VER')
           )
    """))


def _active_map(connection, table):
    return dict(connection.execute(text(
        f"SELECT codigo, activo FROM {table} ORDER BY codigo"
    )).all())


def _effective_codes(connection, role_code):
    return set(connection.execute(text("""
        SELECT capability.codigo
        FROM scm_rol_capacidad relation
        JOIN rol_operativo role
          ON role.id = relation.rol_operativo_id
        JOIN scm_capacidad capability
          ON capability.id = relation.capacidad_id
        WHERE role.codigo = :role_code
          AND role.activo
          AND capability.activo
    """), {"role_code": role_code}).scalars())


def _exercise_guard(connection, monkeypatch):
    _previous_schema(connection)
    relation_count = connection.execute(text(
        "SELECT count(*) FROM scm_rol_capacidad"
    )).scalar_one()
    migration = importlib.import_module(MIGRATION_MODULE)
    monkeypatch.setattr(
        migration,
        "op",
        Operations(MigrationContext.configure(connection)),
    )

    migration.upgrade()
    capabilities = _active_map(connection, "scm_capacidad")
    roles = _active_map(connection, "rol_operativo")
    assert all(not capabilities[code] for code in GUARDED_CAPABILITIES)
    assert all(capabilities[code] for code in K1_CAPABILITIES)
    assert not roles["PREPARADOR_MATERIAL"]
    assert roles["GERENTE_GENERAL"]
    assert _effective_codes(connection, "PREPARADOR_MATERIAL") == set()
    assert _effective_codes(connection, "GERENTE_GENERAL") == (
        K1_CAPABILITIES | {"INVENTARIO_VER"}
    )
    assert connection.execute(text(
        "SELECT count(*) FROM scm_rol_capacidad"
    )).scalar_one() == relation_count

    migration.downgrade()
    capabilities = _active_map(connection, "scm_capacidad")
    roles = _active_map(connection, "rol_operativo")
    # Downgrade is intentionally fail-closed. Re-enabling excluded modules
    # requires a later explicit rollout; no permission is blindly restored.
    assert all(not capabilities[code] for code in GUARDED_CAPABILITIES)
    assert all(capabilities[code] for code in K1_CAPABILITIES)
    assert not roles["PREPARADOR_MATERIAL"]
    assert _effective_codes(connection, "GERENTE_GENERAL") == (
        K1_CAPABILITIES | {"INVENTARIO_VER"}
    )
    assert connection.execute(text(
        "SELECT count(*) FROM scm_rol_capacidad"
    )).scalar_one() == relation_count


def test_pilot_feature_guard_upgrade_downgrade_sqlite(monkeypatch):
    engine = create_engine("sqlite:///:memory:")
    with engine.begin() as connection:
        _exercise_guard(connection, monkeypatch)
    engine.dispose()


def test_pilot_feature_guard_upgrade_downgrade_postgres(monkeypatch):
    database_url = os.getenv("TEST_DATABASE_URL")
    if not database_url:
        pytest.skip("TEST_DATABASE_URL is required for PostgreSQL tests")
    engine = create_engine(database_url, pool_pre_ping=True)
    schema = f"pilot_guard_{uuid4().hex}"
    try:
        with engine.begin() as connection:
            connection.exec_driver_sql(f'CREATE SCHEMA "{schema}"')
            connection.exec_driver_sql(f'SET LOCAL search_path TO "{schema}"')
            _exercise_guard(connection, monkeypatch)
    finally:
        with engine.begin() as connection:
            connection.exec_driver_sql(
                f'DROP SCHEMA IF EXISTS "{schema}" CASCADE'
            )
        engine.dispose()
